services:

  rapt_db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${EXT_MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - rapt_mysql_db_data:/var/local/mysql
      - rapt_mysql_db_config:/etc/mysql

  test_rapt_db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${TEST_DATABASE_PASSWORD}
      - MYSQL_DATABASE=${TEST_DATABASE_NAME}
      - MYSQL_USER=${TEST_DATABASE_USER}
      - MYSQL_PASSWORD=${TEST_DATABASE_PASSWORD}
    ports:
      - 9011:${MYSQL_PORT}

  rapt_service:
    depends_on:
      - rapt_db
    restart: always
    build:
      context: ./service
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - EXT_MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=rapt_db
    ports:
      - "${EXT_SERVICE_PORT}:${SERVICE_PORT}"
    volumes:
      - ./service/:/service/  

volumes:
  rapt_mysql_db_data:
  rapt_mysql_db_config: