services:

  rapt_db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 9010:${MYSQL_PORT}
    volumes:
      - rapt_mysql_db_data:/var/local/mysql
      - rapt_mysql_db_config:/etc/mysql

  test_rapt_db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${TEST_DATABASE_PASSWORD}
      - MYSQL_DATABASE=${TEST_DATABASE_NAME}
      - MYSQL_USER=${TEST_DATABASE_USER}
      - MYSQL_PASSWORD=${TEST_DATABASE_PASSWORD}
    ports:
      - 9011:${MYSQL_PORT}

volumes:
  rapt_mysql_db_data:
  rapt_mysql_db_config: