"""remake db

Revision ID: 175851a3c2f5
Revises: e0e9f5251901
Create Date: 2024-10-07 01:21:31.417494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175851a3c2f5'
down_revision: Union[str, None] = 'e0e9f5251901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'contacts', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_column('contacts', 'id')
    # ### end Alembic commands ###
