"""remake db

Revision ID: e0e9f5251901
Revises: f85cbffca5f5
Create Date: 2024-10-07 01:06:54.380121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e9f5251901'
down_revision: Union[str, None] = 'f85cbffca5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_contact', 'contacts', ['user_id', 'contact_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_contact', 'contacts', type_='unique')
    # ### end Alembic commands ###
