"""update phone

Revision ID: ecb8a11e3dd4
Revises: 05518989234b
Create Date: 2024-09-30 01:56:38.951433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ecb8a11e3dd4'
down_revision: Union[str, None] = '05518989234b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('name', sa.String(length=50), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=False)
    op.drop_column('contacts', 'name')
    # ### end Alembic commands ###
